# Generated by Django 3.0 on 2022-02-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_detail',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
